add_test( [==[Test InvalufIDs Commands]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Test InvalufIDs Commands]==]  )
set_tests_properties( [==[Test InvalufIDs Commands]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Test AVL Rotations]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Test AVL Rotations]==]  )
set_tests_properties( [==[Test AVL Rotations]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Large Scale Insert and Remove Test]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Large Scale Insert and Remove Test]==]  )
set_tests_properties( [==[Large Scale Insert and Remove Test]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Test removeInorder functionality]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Test removeInorder functionality]==]  )
set_tests_properties( [==[Test removeInorder functionality]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Comprehensive Tree Operations Test]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Comprehensive Tree Operations Test]==]  )
set_tests_properties( [==[Comprehensive Tree Operations Test]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
set( Tests_TESTS [==[Test InvalufIDs Commands]==] [==[Test AVL Rotations]==] [==[Large Scale Insert and Remove Test]==] [==[Test removeInorder functionality]==] [==[Comprehensive Tree Operations Test]==])
