add_test( [==[Random Removal in a Loop Using removeInorder]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Random Removal in a Loop Using removeInorder]==]  )
set_tests_properties( [==[Random Removal in a Loop Using removeInorder]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Insertion and Search with Edge UFIDs]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Insertion and Search with Edge UFIDs]==]  )
set_tests_properties( [==[Insertion and Search with Edge UFIDs]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Remove Inorder on Single Node Tree]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Remove Inorder on Single Node Tree]==]  )
set_tests_properties( [==[Remove Inorder on Single Node Tree]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Invalid Insert Commands]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Invalid Insert Commands]==]  )
set_tests_properties( [==[Invalid Insert Commands]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Inserting and Searching for a Single Node]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Inserting and Searching for a Single Node]==]  )
set_tests_properties( [==[Inserting and Searching for a Single Node]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Invalid Insert Commands]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Invalid Insert Commands]==]  )
set_tests_properties( [==[Invalid Insert Commands]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Insertion and Basic Search]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Insertion and Basic Search]==]  )
set_tests_properties( [==[Insertion and Basic Search]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Duplicate Insertions]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Duplicate Insertions]==]  )
set_tests_properties( [==[Duplicate Insertions]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Insertion and Removal by Key]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Insertion and Removal by Key]==]  )
set_tests_properties( [==[Insertion and Removal by Key]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Remove Inorder by Index]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Remove Inorder by Index]==]  )
set_tests_properties( [==[Remove Inorder by Index]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Traversal Orders]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Traversal Orders]==]  )
set_tests_properties( [==[Traversal Orders]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Tree Level Count on Empty and Non-empty Trees]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Tree Level Count on Empty and Non-empty Trees]==]  )
set_tests_properties( [==[Tree Level Count on Empty and Non-empty Trees]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Search By Name]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Search By Name]==]  )
set_tests_properties( [==[Search By Name]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Insertion With Leading and Trailing Spaces]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Insertion With Leading and Trailing Spaces]==]  )
set_tests_properties( [==[Insertion With Leading and Trailing Spaces]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Forced Rotations and Balancing]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Forced Rotations and Balancing]==]  )
set_tests_properties( [==[Forced Rotations and Balancing]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Sequential Removal (Remove Inorder Until Empty)]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Sequential Removal (Remove Inorder Until Empty)]==]  )
set_tests_properties( [==[Sequential Removal (Remove Inorder Until Empty)]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Random Removal Loop Until Empty]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Random Removal Loop Until Empty]==]  )
set_tests_properties( [==[Random Removal Loop Until Empty]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
set( Tests_TESTS [==[Random Removal in a Loop Using removeInorder]==] [==[Insertion and Search with Edge UFIDs]==] [==[Remove Inorder on Single Node Tree]==] [==[Invalid Insert Commands]==] [==[Inserting and Searching for a Single Node]==] [==[Invalid Insert Commands]==] [==[Insertion and Basic Search]==] [==[Duplicate Insertions]==] [==[Insertion and Removal by Key]==] [==[Remove Inorder by Index]==] [==[Traversal Orders]==] [==[Tree Level Count on Empty and Non-empty Trees]==] [==[Search By Name]==] [==[Insertion With Leading and Trailing Spaces]==] [==[Forced Rotations and Balancing]==] [==[Sequential Removal (Remove Inorder Until Empty)]==] [==[Random Removal Loop Until Empty]==])
