if(EXISTS "/home/adios/COP3530/AVLtreeTest/build_debug/Tests-b12d07c_tests.cmake")
  include("/home/adios/COP3530/AVLtreeTest/build_debug/Tests-b12d07c_tests.cmake")
else()
  add_test(Tests_NOT_BUILT-b12d07c Tests_NOT_BUILT-b12d07c)
endif()
