add_test( [==[Test InvalufIDs Commands]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Test InvalufIDs Commands]==]  )
set_tests_properties( [==[Test InvalufIDs Commands]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Test AVL Rotations]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Test AVL Rotations]==]  )
set_tests_properties( [==[Test AVL Rotations]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Large Scale Insert and Remove Test]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Large Scale Insert and Remove Test]==]  )
set_tests_properties( [==[Large Scale Insert and Remove Test]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Test removeInorder functionality]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Test removeInorder functionality]==]  )
set_tests_properties( [==[Test removeInorder functionality]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Comprehensive Tree Operations Test]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Comprehensive Tree Operations Test]==]  )
set_tests_properties( [==[Comprehensive Tree Operations Test]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Additional Random Mixed Operations Test]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Additional Random Mixed Operations Test]==]  )
set_tests_properties( [==[Additional Random Mixed Operations Test]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Random Comprehensive Full Test]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Random Comprehensive Full Test]==]  )
set_tests_properties( [==[Random Comprehensive Full Test]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Empty Tree Operations Test]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Empty Tree Operations Test]==]  )
set_tests_properties( [==[Empty Tree Operations Test]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Single Node Operations Test]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Single Node Operations Test]==]  )
set_tests_properties( [==[Single Node Operations Test]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Stress Test with Many Random Operations]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Stress Test with Many Random Operations]==]  )
set_tests_properties( [==[Stress Test with Many Random Operations]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Traversal Integrity Test]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Traversal Integrity Test]==]  )
set_tests_properties( [==[Traversal Integrity Test]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Boundary Conditions Test]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Boundary Conditions Test]==]  )
set_tests_properties( [==[Boundary Conditions Test]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Rotation Specific Tests]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Rotation Specific Tests]==]  )
set_tests_properties( [==[Rotation Specific Tests]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Sequential Removal Test]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Sequential Removal Test]==]  )
set_tests_properties( [==[Sequential Removal Test]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Massive Random Operations Test]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Massive Random Operations Test]==]  )
set_tests_properties( [==[Massive Random Operations Test]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Duplicate Insertion Test]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Duplicate Insertion Test]==]  )
set_tests_properties( [==[Duplicate Insertion Test]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Large Scale Sequential Insertions Test]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Large Scale Sequential Insertions Test]==]  )
set_tests_properties( [==[Large Scale Sequential Insertions Test]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Large Scale Sequential Removals Test]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Large Scale Sequential Removals Test]==]  )
set_tests_properties( [==[Large Scale Sequential Removals Test]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Mixed Operation Count Test]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Mixed Operation Count Test]==]  )
set_tests_properties( [==[Mixed Operation Count Test]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Duplicate and Re-Insert Test]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Duplicate and Re-Insert Test]==]  )
set_tests_properties( [==[Duplicate and Re-Insert Test]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Randomized Rotation Consistency Test]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Randomized Rotation Consistency Test]==]  )
set_tests_properties( [==[Randomized Rotation Consistency Test]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Tree Stability Under Repeated Operations]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Tree Stability Under Repeated Operations]==]  )
set_tests_properties( [==[Tree Stability Under Repeated Operations]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Stress Test with Limited UFID Range]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Stress Test with Limited UFID Range]==]  )
set_tests_properties( [==[Stress Test with Limited UFID Range]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Full Traversal Validation Under Load]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Full Traversal Validation Under Load]==]  )
set_tests_properties( [==[Full Traversal Validation Under Load]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[1000 Insertions, 1000 Removals, and Final Consistency]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[1000 Insertions\, 1000 Removals\, and Final Consistency]==]  )
set_tests_properties( [==[1000 Insertions, 1000 Removals, and Final Consistency]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Randomized Insert]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Randomized Insert]==]  )
set_tests_properties( [==[Randomized Insert]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Randomized Remove]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Randomized Remove]==]  )
set_tests_properties( [==[Randomized Remove]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Randomized Search]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Randomized Search]==]  )
set_tests_properties( [==[Randomized Search]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Randomized RemoveInorder]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Randomized RemoveInorder]==]  )
set_tests_properties( [==[Randomized RemoveInorder]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Randomized Operations]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Randomized Operations]==]  )
set_tests_properties( [==[Randomized Operations]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Randomized Operations with Limited UFID Range]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Randomized Operations with Limited UFID Range]==]  )
set_tests_properties( [==[Randomized Operations with Limited UFID Range]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Randomized Operatoins with Limited UFID Range]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Randomized Operatoins with Limited UFID Range]==]  )
set_tests_properties( [==[Randomized Operatoins with Limited UFID Range]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Test case to test inorder postorder and preorder]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Test case to test inorder postorder and preorder]==]  )
set_tests_properties( [==[Test case to test inorder postorder and preorder]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Test case to test level count]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Test case to test level count]==]  )
set_tests_properties( [==[Test case to test level count]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Test case to test random insertions]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Test case to test random insertions]==]  )
set_tests_properties( [==[Test case to test random insertions]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[random test case to insert unique nodes]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[random test case to insert unique nodes]==]  )
set_tests_properties( [==[random test case to insert unique nodes]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
add_test( [==[Randomized Operations with Limited UFID Range]==] /home/adios/COP3530/AVLtreeTest/build_debug/Tests [==[Randomized Operations with Limited UFID Range]==]  )
set_tests_properties( [==[Randomized Operations with Limited UFID Range]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_debug)
set( Tests_TESTS [==[Test InvalufIDs Commands]==] [==[Test AVL Rotations]==] [==[Large Scale Insert and Remove Test]==] [==[Test removeInorder functionality]==] [==[Comprehensive Tree Operations Test]==] [==[Additional Random Mixed Operations Test]==] [==[Random Comprehensive Full Test]==] [==[Empty Tree Operations Test]==] [==[Single Node Operations Test]==] [==[Stress Test with Many Random Operations]==] [==[Traversal Integrity Test]==] [==[Boundary Conditions Test]==] [==[Rotation Specific Tests]==] [==[Sequential Removal Test]==] [==[Massive Random Operations Test]==] [==[Duplicate Insertion Test]==] [==[Large Scale Sequential Insertions Test]==] [==[Large Scale Sequential Removals Test]==] [==[Mixed Operation Count Test]==] [==[Duplicate and Re-Insert Test]==] [==[Randomized Rotation Consistency Test]==] [==[Tree Stability Under Repeated Operations]==] [==[Stress Test with Limited UFID Range]==] [==[Full Traversal Validation Under Load]==] [==[1000 Insertions, 1000 Removals, and Final Consistency]==] [==[Randomized Insert]==] [==[Randomized Remove]==] [==[Randomized Search]==] [==[Randomized RemoveInorder]==] [==[Randomized Operations]==] [==[Randomized Operations with Limited UFID Range]==] [==[Randomized Operatoins with Limited UFID Range]==] [==[Test case to test inorder postorder and preorder]==] [==[Test case to test level count]==] [==[Test case to test random insertions]==] [==[random test case to insert unique nodes]==] [==[Randomized Operations with Limited UFID Range]==])
