add_test( [==[Example Test Name - Change me!]==] /home/adios/COP3530/AVLtreeTest/build_release/Tests [==[Example Test Name - Change me!]==]  )
set_tests_properties( [==[Example Test Name - Change me!]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_release)
add_test( [==[Test 2]==] /home/adios/COP3530/AVLtreeTest/build_release/Tests [==[Test 2]==]  )
set_tests_properties( [==[Test 2]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_release)
add_test( [==[Example BST Insert]==] /home/adios/COP3530/AVLtreeTest/build_release/Tests [==[Example BST Insert]==]  )
set_tests_properties( [==[Example BST Insert]==] PROPERTIES WORKING_DIRECTORY /home/adios/COP3530/AVLtreeTest/build_release)
set( Tests_TESTS [==[Example Test Name - Change me!]==] [==[Test 2]==] [==[Example BST Insert]==])
